site:
  title: Personal Documentation Site
  # the 404 page and sitemap files only get generated when the url property is set
  #url: https://klopfy.ca/docs-site
  start_page: homelab::ansible.adoc
content:
  sources:
  - url: https://github.com/Klopfy/antora.git
    branches: HEAD
    tags: [alpha]
  - url: https://gitlab.com/antora/antora.git
    start_path: docs
    branches: v3.1.x
    edit_url: false

runtime:
  cache_dir: ./.cache/antora

asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    kroki-server-url: 'https://kroki.io'
    kroki-fetch-diagram: true
    kroki-http-method: "post"
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'

ui:
  bundle:
    url: ./ui-bundle.zip

antora:
  extensions:
    - require: '@springio/antora-extensions/asciinema-extension'
    - require: '@antora/lunr-extension'
      languages: [en, fr]
